# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c485bea6fc6d55e6fbd95c904258eeb20f313cb3b6e33d88a7a5de49c7e269035c99fa46db8a174c65f3c5718bd42091fa1a0fdbc727a27095adab3d8d577c2

test:
  secret_key_base: 7dc4d70023b6753e79a3cce6309c1fb0b182eb3168190d40913ffe067fec6dcacca7830eafb3aa3de11172a1cb6746270fa94d46185e905420274c5c16c5403b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
